#!/bin/sh
set -e
# Hide Debian's files so Vane can take over
dpkg-divert --package vane-branding --add --rename --divert /etc/os-release.distrib /etc/os-release
dpkg-divert --package vane-branding --add --rename --divert /etc/default/grub.distrib /etc/default/grub
exit 0
